FROM node:16-alpine3.14

WORKDIR /usr/src/app

COPY . .

RUN npm install

RUN npm run build

# Get secret from git action
ARG DATABASE_HOST
ARG DATABASE_PORT
ARG DATABASE_USERNAME
ARG DATABASE_PASSWORD
ARG DATABASE_NAME
ARG JWT_SECRET
ARG ACCESS_TOKEN_EXPIRE
ARG REFRESH_TOKEN_EXPIRE
ARG S3_ACCESS_KEY
ARG S3_SECRET_KEY
ARG S3_BUCKET_NAME
ARG S3_REGION
ARG SLACK_BOT_TOKEN
ARG SLACK_NEW_USER_CHANNEL_ID
ARG SLACK_API_LATENCY_CHANNEL_ID
ARG SLACK_FATAL_ERROR_CHANNEL_ID


# Copy secret to ENV
ENV NODE_ENV=production \
 DATABASE_HOST=$DATABASE_HOST \
 DATABASE_PORT=$DATABASE_PORT \
 DATABASE_USERNAME=$DATABASE_USERNAME \
 DATABASE_PASSWORD=$DATABASE_PASSWORD \
 DATABASE_NAME=$DATABASE_NAME \
 JWT_SECRET=$JWT_SECRET \
 ACCESS_TOKEN_EXPIRE=$ACCESS_TOKEN_EXPIRE \
 REFRESH_TOKEN_EXPIRE=$REFRESH_TOKEN_EXPIRE \
 S3_ACCESS_KEY=$S3_ACCESS_KEY \
 S3_SECRET_KEY=$S3_SECRET_KEY \
 S3_BUCKET_NAME=$S3_BUCKET_NAME \
 S3_REGION=$S3_REGION \
 S3_REGION=$SLACK_BOT_TOKEN \
 S3_REGION=$SLACK_NEW_USER_CHANNEL_ID \
 S3_REGION=$SLACK_API_LATENCY_CHANNEL_ID \
 S3_REGION=$SLACK_FATAL_ERROR_CHANNEL_ID

EXPOSE 3000

CMD ["node", "dist/main"]
