FROM node:16-alpine3.14

WORKDIR /usr/src/app

COPY . .

RUN npm install

RUN npm run build

# Get secret from git action
ARG DATABASE_HOST
ARG DATABASE_PORT
ARG DATABASE_USERNAME
ARG DATABASE_PASSWORD
ARG DATABASE_NAME
ARG JWT_SECRET
ARG ACCESS_TOKEN_EXPIRE
ARG REFRESH_TOKEN_EXPIRE


# Copy secret to ENV
ENV NODE_ENV=production \
 DATABASE_HOST=$DATABASE_HOST \
 DATABASE_PORT=$DATABASE_PORT \
 DATABASE_USERNAME=$DATABASE_USERNAME \
 DATABASE_PASSWORD=$DATABASE_PASSWORD \
 DATABASE_NAME=$DATABASE_NAME \
 JWT_SECRET=$JWT_SECRET \
 ACCESS_TOKEN_EXPIRE=$ACCESS_TOKEN_EXPIRE \
 REFRESH_TOKEN_EXPIRE=$REFRESH_TOKEN_EXPIRE

EXPOSE 3000

CMD ["node", "dist/main"]
